### ISSUE TITLE
Move motif34lib.mat to resources folder

### ISSUE THREAD

**Issue by tsalo** [fiuneuro/brainconn#22]
@adamkimbler You're more familiar with `bctpy` than I am. Do you think there's some way to eliminate the need for motif34lib.mat? If not, I recommend that we make a folder called resources, move the file there, and add a util function called `get_resource_path`. That's an approach I've used in the past and have seen in other packages, and I think it's a little more aesthetically pleasing than keeping the file at the top level. WDYT?

**Comment by adamkimbler** [comment]
@tsalo I've never actually looked within that particular code, but it's likely that we could just translate the code from Matlab to python. I've not paid too much attention to the Motifs functions.

**Comment by tsalo** [comment]
Why don't we move it for `0.0.2` and open an issue to translate to Python for `1.0.0`?
